# Generated by Django 4.2.4 on 2023-08-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesureanimal',
            name='mesure_date',
            field=models.DateField(),
        ),
    ]
